# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'Weekand' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weekand

  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'AlignedCollectionViewFlowLayout'

  # UIKit
  pod 'SnapKit'
  pod 'Then'
  
  # Cooperation
  pod 'SwiftLint'

  # Calender
  pod 'FSCalendar'

  # Apollo
  pod 'Apollo'

  # DropDown
  pod 'DropDown', '2.3.13'

end