# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'Weekand' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weekand

  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'AlignedCollectionViewFlowLayout'

  # UIKit
  pod 'SnapKit'
  pod 'Then'
  
  # Cooperation
  pod 'SwiftLint'

end
